from . import res_company
from . import account_account
from . import tax
from . import product_template
from . import res_partner_category
from . import res_partner
from . import sale_order
from . import purchase_order
from . import invoice
from . import account_payments
from . import maintain_logs
from . import dashboard
from . import xero_logger
